### ISSUE TITLE
View Media: Openseadragon icons not loaded  

### ISSUE THREAD

**Issue by Falteri** [omeka/omeka-s#1202]
It seems that in view media, openseadragon icons are not visible, e.g. http://www.cennino.it/application/asset/vendor/openseadragon/images/?v=1.1.0-alphazoomin_rest.png

**Comment by zerocrates** [comment]
Yeah, I noticed this as well, in #1191, as did @Daniel-KM, and he sent a PR that fixes the problem (well before I even filed my issue about it).

That change is merged, so the problem should be fixed in the next release of Omeka S.

I'm going to close this as a duplicate.

**Comment by zerocrates** [comment]
One note: I see you're using 1.1.0-alpha, or the develop branch on Git in other words. If you're up to date on that, you shouldn't see this problem anymore.

**Comment by Falteri** [comment]
I saw issue 1191 before the 1202 and I think I should be up to date at the latest version of develop, but I still have this issue. Maybe I’ve made something wrong with git ...
I’ll try to double check. Thanks for replying.

Inviato da iPhone
