### ISSUE TITLE
Testing: Site Navigation

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#420]
Add a new site and add a few pages to it. On the "Navigation" panel of site edit add a bunch of custom links and page links then go crazy dragging-and-dropping and editing the links. Save and see if your changes were actually saved. Remove a few nodes, save, and see if they were actually removed. What can we do to make it more usable?

**Comment by alyssafahringer** [comment]
I get the following error message after I've added a custom URL and then choose "select below" in the dropdown menu: 
![screen shot 2015-10-14 at 1 57 17 pm](https://cloud.githubusercontent.com/assets/8807816/10492715/83145f2a-727b-11e5-811b-ed96a6e76619.png)

**Comment by alyssafahringer** [comment]
Page says loading after I edited three custom URLs and removed the two new nodes with error messages. It's been a few minutes now and the page hasn't populated 
![screen shot 2015-10-14 at 2 09 58 pm](https://cloud.githubusercontent.com/assets/8807816/10493137/813e6e00-727d-11e5-9ff3-4f2c0bd3730c.png)

**Comment by alyssafahringer** [comment]
This is the error message I get when looking at the public-facing side of "SecondSite"

There was an error.

exception 'Zend\Mvc\Router\Exception\RuntimeException' with message 'Route with name "browse" not found' in /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Router/Http/TreeRouteStack.php:317
Stack trace:
#0 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Router/Http/Part.php(210): Zend\Mvc\Router\Http\TreeRouteStack->assemble(Array, Array)
#1 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Router/Http/TreeRouteStack.php(351): Zend\Mvc\Router\Http\Part->assemble(Array, Array)
#2 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-view/src/Helper/Url.php(100): Zend\Mvc\Router\Http\TreeRouteStack->assemble(Array, Array)
#3 [internal function]: Zend\View\Helper\Url->__invoke('site/browse', Array, Array, true)
#4 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(393): call_user_func_array(Object(Zend\View\Helper\Url), Array)
#5 /websites/omekadev/home/www/omeka-s/application/src/BlockLayout/BrowsePreview.php(53): Zend\View\Renderer\PhpRenderer->__call('url', Array)
#6 /websites/omekadev/home/www/omeka-s/application/src/BlockLayout/BrowsePreview.php(53): Zend\View\Renderer\PhpRenderer->url('site/browse', Array, Array, true)
#7 /websites/omekadev/home/www/omeka-s/application/src/View/Helper/BlockLayout.php(103): Omeka\BlockLayout\BrowsePreview->render(Object(Zend\View\Renderer\PhpRenderer), Object(Omeka\Api\Representation\SitePageBlockRepresentation))
#8 /websites/omekadev/home/www/omeka-s/application/view-shared/omeka/site/page/show.phtml(5): Omeka\View\Helper\BlockLayout->render(Object(Omeka\Api\Representation\SitePageBlockRepresentation))
#9 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(501): include('/websites/omeka...')
#10 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-view/src/View.php(205): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel))
#11 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-view/src/View.php(233): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#12 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-view/src/View.php(198): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#13 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(103): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#14 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#15 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent), Array)
#17 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(353): Zend\EventManager\EventManager->trigger('render', Object(Zend\Mvc\MvcEvent))
#18 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(328): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#19 /websites/omekadev/home/www/omeka-s/index.php(16): Zend\Mvc\Application->run()
#20 {main}

**Comment by jimsafley** [comment]
@alyssafahringer I fixed https://github.com/omeka/omeka-s/issues/420#issuecomment-148136069. Unfortunately, for https://github.com/omeka/omeka-s/issues/420#issuecomment-148141316 you'll need to delete the site and add another one; the navigation data is corrupted. Pull and try again.

I'm still looking into https://github.com/omeka/omeka-s/issues/420#issuecomment-148142635.

**Comment by jimsafley** [comment]
@alyssafahringer https://github.com/omeka/omeka-s/issues/420#issuecomment-148142635 should be fixed. Pull and try again.

**Comment by alyssafahringer** [comment]
I'm still getting the same error message after adding a custom URL and choosing select below in the dropdown menu. I deleted the old site and added another one - had it happen with both third and fourth sites.

**Comment by jimsafley** [comment]
You're browser is probably caching the old JavaScript. Make sure you have pulled the changes and do a hard reload in your browser. You'll have to continue deleting the site until this works.

**Comment by mebrett** [comment]
The issue was that somehow "select below" became an option for her to add a block on the navigation, which created a funky node. I can't replicate it on Chrome on my machine but it's something to be aware of.

**Comment by jimsafley** [comment]
After my changes that shouldn't be possible unless her browser is using the older, cached JS.

**Comment by alyssafahringer** [comment]
Fixed
